# Generated by Django 5.0.6 on 2025-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ioc',
            field=models.BooleanField(default=False),
        ),
    ]
