# Generated by Django 4.2.17 on 2025-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disclosed',
            field=models.IntegerField(default=0),
        ),
    ]
