# Generated by Django 5.1.4 on 2025-03-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_triggered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="limit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stop_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_mode",
            field=models.CharField(
                choices=[
                    ("LIMIT", "Limit"),
                    ("MARKET", "Market"),
                    ("STOP_MARKET", "Stop Market"),
                    ("STOP_LIMIT", "Stop Limit"),
                ],
                max_length=15,
            ),
        ),
    ]
