# Generated by Django 4.2.17 on 2025-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_stoploss_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoploss_order',
            name='end_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
