# Generated by Django 4.2.17 on 2025-01-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_stoploss_order_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoploss_order',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
