# Generated by Django 4.2.17 on 2025-01-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_stoploss_order_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoploss_order',
            name='end_time',
        ),
    ]
