# Generated by Django 5.0.6 on 2025-02-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_stoploss_order_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
